language: node_js
node_js:
- "8"
sudo: required
dist: trusty

before_install:
  - chmod +x deployCloudFoundry.sh

install:
  - sudo apt-get install ghostscript
  - sudo apt-get install libgs-dev
  - sudo ln -s /usr/lib/libgs.so /usr/lib/x86_64-linux-gnu/libgs.so
  - sudo apt-get install tesseract-ocr
  - sudo apt-get install libtesseract-dev
  - npm i -g jasmine
  - npm i -g istanbul
  - npm i

script:
  # Coverage check
  - istanbul cover ./node_modules/jasmine/bin/jasmine.js

before_deploy:
  - export TESSDATA_PREFIX=~/Downloads/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./deployCloudFoundry.sh
    on:
      type: push
      branch:
        - travis_test
